# Generated by Django 4.1.7 on 2023-04-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransitLinkApp', '0001_initial'),
    ]

    operations = [
    ]
