# Generated by Django 4.1.7 on 2023-04-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransitLinkApp', '0002_auto_20230402_2348'),
    ]

    operations = [
    ]
