# Generated by Django 4.1.7 on 2023-04-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransitApp', '0001_initial'),
    ]

    operations = [
    ]
